//! SCIP protobuf types generated by prost
//!
//! This module includes the prost-generated types from the SCIP proto definition.

#[allow(clippy::all)]
#[allow(missing_docs)]
#[allow(rustdoc::invalid_codeblock_attributes)]
include!(concat!(env!("OUT_DIR"), "/scip.rs"));
