//! SCIP protobuf types generated by prost
//!
//! This module includes the prost-generated types from the SCIP proto definition.
//! Doc comments are disabled in build.rs to avoid doctest failures from upstream
//! SCIP proto examples that aren't valid Rust code.

include!(concat!(env!("OUT_DIR"), "/scip.rs"));
